version: "3.7"
services:
  database:
    image: mysql:8.0
    ports: 
        - "3306:3306"
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_DATABASE: base
        MYSQL_ROOT_PASSWORD: test 
    volumes:
        - ./dump:/docker-entrypoint-initdb.d
        - ./php:/etc/mysql/conf.d
        - persistent:/var/lib/mysql
    networks:
        - default
  php-apache:
    build:
      context: .
      dockerfile: php.Dockerfile
    ports:
        - '80:80'
    volumes:
      - ./src:/var/www/api-rest-laravel
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8000:80"
    environment:
        PMA_HOST: database
        MYSQL_USER: root
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
    depends_on:
      - database
    networks:
      - default
volumes:
  persistent:
  